# Your sample configuration should be looks like this:
# There are three levels:
# 1. Different samples.
# 2. Each sample contains multiple biological replicates(biosamples)
# 3. Each biosample contains multiple technical replicates(experiments)
#
# notation: file parameters: filepath and url are both supported.(Downloading will take much time.)
# notation: sra file: SRR number or local sra file are supported.
# notation: glob syntax: The returned number of files should be even.(Only support for paired-end mode.)
#
#raw_reads:
#    sample1:
#        bio1:
#            - 'x06_1.fastq'
#            - 'x06_2.fastq'
#        bio2:
#            - 'https://url....lane1_1.fastq.gz'
#            - 'lane1_2.fastq'
#            - 'lane[4,5,6]*fastq'
#            - 'lane10*'
#    sample2:
#        bio1:
#            - 'SRR2601843'
#            - 'x07_1.fastq'
#            - 'x07_2.fastq'


index: "index/hg19.bwa"
chromsize: "http://genome.ucsc.edu/goldenpath/help/hg19.chrom.sizes"
stat: true
fastqc: true
fastq_dump_threads: 10
map:
    assembly: "hg19"
    genome: '/store/qzhong/tmp/hic/hg19.fa'
    chunksize: 400000
    merge_bam: true
parse:
    parse_args: "--min-mapq 0 --drop-sam --drop-seq --drop-readid"
    sort_tmpdir: '/tmp'
filter:
    frag_path: ''
    enzyme: 'HindIII'
#    filter_expr: "((pair_type=='UU') or (pair_type=='UR') or (pair_type=='RU')) and not ((COLS[-6]==COLS[-3]) and (chrom1==chrom2))"
    filter_expr: "((pair_type=='UU') or (pair_type=='UR') or (pair_type=='RU'))"
resulotions:
    - 10000
    - 50000
    - 100000
    - 1000000
