name: hictools
channels:
    - conda-forge
    - bioconda
    - hcc
dependencies:
    - python >= 3.7
    - pip
    - pbgzip
    - lz4-c
    - bwa = 0.7.17
    - samtools
    - sra-tools
    - aspera-cli
    - pairix
    - fastqc
    - parallel-fastq-dump   
    - pip:
        - multiqc
        - decorator >= 4.1.0
