name: hictools
channels:
    - conda-forge
    - bioconda
    - hcc
dependencies:
    - python >= 3.7
    - pip
    - pbgzip
    - lz4-c
    - bwa = 0.7.17
    - samtools
    - sra-tools
    - aspera-cli
    - pairix
    - fastqc
    - parallel-fastq-dump   
    - pairtools
    - nginx
    - cooler >= 0.8.6
    - pysam
    - pyBigWig
    - Cython >= 0.29.13
    - numpy >= 1.17.0
    - scipy >= 1.3.1
    - matplotlib >= 3.1.1
    - pip:
        - multiqc
        - decorator >= 4.1.0
        - wget
        - h5py
        - pytest
        - Click >= 7.0
        - pandas >= 0.25.0
        - ray >= 0.7.3
        - setproctitle>=1.1.10
        - scikit-learn >= 0.21.3
        - twine>=1.13.0
        - pomegranate>=0.11.0
        - statsmodels>=0.10.1
        - fire
        - uvicorn
        - starlette
        - fastapi
        - ujson
        - watchgod
        - slugid
        - clodius
        - sqlalchemy
        - databases
        - aiosqlite
