name: hicpipeline
channels:
    - conda-forge
    - bioconda
    - hcc
dependencies:
    - python >= 3.7
    - pip
    - pbgzip
    - lz4-c
    - bwa
    - samtools
    - sra-tools
    - aspera-cli
    - pairix
    - fastqc
    - parallel-fastq-dump   
    - pairtools
    - cooler
    - pip:
        - cython
        - numpy
        - scipy
        - pandas
        - matplotlib
        - multiqc
        - decorator >= 4.1.0
        - ray
        - scikit-learn
        - statsmodels
        - pomegranate

